### ISSUE TITLE
Handle `disable_on_timeout` in DMs

### ISSUE THREAD

**Issue by tibue99** [Pycord-Development/pycord#2726]
### Summary

In some cases, view buttons are not disabled in DMs when `disable_on_timeout` is set to `True`.

### Reproduction Steps

1. Run `/party`
2. Click the button
3. Wait for timeout

### Minimal Reproducible Code

```python
import discord

bot = discord.Bot()

class PartyButton(discord.ui.View):
    def __init__(self):
        super().__init__(timeout=10, disable_on_timeout=True)

    @discord.ui.button(label="Party")
    async def party(self, button, interaction):
        await interaction.edit(content="🎉")


@bot.slash_command(
    contexts={discord.InteractionContextType.private_channel},
    integration_types={discord.IntegrationType.user_install},
)
async def party(ctx):
    await ctx.respond(view=PartyButton())

bot.run("")
```

### Expected Results

Button gets disabled

### Actual Results

```
Task exception was never retrieved
future: <Task finished name='discord-ui-view-timeout-37f1819640748e5c45353904a3edb8d9' coro=<View.on_timeout() done, defined at C:\Users\Timo\Desktop\cookie\.venv\Lib\site-packages\discord\ui\view.py:364> exception=Forbidden('403 Forbidden (error code: 50001): Missing Access')>
Traceback (most recent call last):
  File "C:\Users\Timo\Desktop\cookie\.venv\Lib\site-packages\discord\ui\view.py", line 381, in on_timeout
    m = await message.edit(view=self)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Timo\Desktop\cookie\.venv\Lib\site-packages\discord\message.py", line 1634, in edit
    data = await self._state.http.edit_message(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        self.channel.id, self.id, **payload
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\Timo\Desktop\cookie\.venv\Lib\site-packages\discord\http.py", line 371, in request
    raise Forbidden(response, data)
discord.errors.Forbidden: 403 Forbidden (error code: 50001): Missing Access
```

### Intents

-

### System Information

- Python v3.13.0-final
- py-cord v2.6.1-final
- aiohttp v3.11.12
- system info: Windows 11 10.0.26100

### Checklist

- [x] I have searched the open issues for duplicates.
- [x] I have shown the entire traceback, if possible.
- [x] I have removed my token from display, if visible.

### Additional Context

The `on_timeout` event contains the following code
```py
            if not self._message or self._message.flags.ephemeral:
                message = self.parent
            else:
                message = self.message
```

The button would be disabled correctly if `self.parent` would be used for editing. However, due to the condition it uses `self.message`, which trows an error.

**Comment by Soheab** [comment]
I cannot repro this on the latest commit using the provided code. I assume this was fixed in some commit.

**Comment by tibue99** [comment]
> I cannot repro this on the latest commit using the provided code. I assume this was fixed in some commit.

@Soheab I still get the exact same error on master. Note that the command is executed in a private chat (not the bot's DMs)

**Comment by Soheab** [comment]
> @Soheab I still get the exact same error on master. Note that the command is executed in a private chat (not the bot's DMs)

Weird, I tried all three contexts, and it edited the button just fine.

**Comment by tibue99** [comment]
> Weird, I tried all three contexts, and it edited the button just fine.

Here is some additional context with some prints in the `on_timeout` event.
```py
    async def on_timeout(self) -> None:
        if self.disable_on_timeout:
            self.disable_all_items()

            print("_Message", self._message)
            print("Parent", self.parent)
            print("Message", self.message)

            if not self._message or self._message.flags.ephemeral:
                message = self.parent
            else:
                message = self.message

            if message:
                m = await message.edit(view=self)
```

When I don't click the button, the timeout works fine:
```
_Message <InteractionMessage id=1432309319382073434 channel=<DMChannel id=760499951536177182 recipient=<User id=665458491187527680 username='chase_stinkt' global_name='GigaChad' bot=False>> type=<MessageType.application_command: 20> author=<User id=986595646914068480 name='Tutorial Bot' discriminator='3708' bot=True> flags=<MessageFlags value=0>>
Parent <discord.interactions.Interaction object at 0x000001E141ED8180>
Message <InteractionMessage id=1432309319382073434 channel=<DMChannel id=760499951536177182 recipient=<User id=665458491187527680 username='chase_stinkt' global_name='GigaChad' bot=False>> type=<MessageType.application_command: 20> author=<User id=986595646914068480 name='Tutorial Bot' discriminator='3708' bot=True> flags=<MessageFlags value=0>>
```
When I click the button, the values change and the timeout event results in a `Missing Access` error.
```
_Message <Message id=1432310795449925642 channel=<DMChannel id=760499951536177182 recipient=<User id=665458491187527680 username='chase_stinkt' global_name='GigaChad' bot=False>> type=<MessageType.application_command: 20> author=<User id=986595646914068480 name='Tutorial Bot' discriminator='3708' bot=True> flags=<MessageFlags value=0>>
Parent <discord.interactions.Interaction object at 0x000001E141ED9D00>
Message <Message id=1432310795449925642 channel=<DMChannel id=760499951536177182 recipient=<User id=665458491187527680 username='chase_stinkt' global_name='GigaChad' bot=False>> type=<MessageType.application_command: 20> author=<User id=986595646914068480 name='Tutorial Bot' discriminator='3708' bot=True> flags=<MessageFlags value=0>>
```
Because `self._message` has a valid value, `self.message` is used for editing. However, message edits without interactions are not possible in private chats and `self.parent` should be used instead.
