### ISSUE TITLE
`Option` with empty string as default results in None

### ISSUE THREAD

**Issue by Snawe** [Pycord-Development/pycord#310]
### Summary

If you add a slash_command with `Option(str, "stuff", required=False, default="")` the parameter defaults to None

### Reproduction Steps

* Make a slash command
* add an Option with a default value
* Check the default value

### Minimal Reproducible Code

```python
from discord.commands.commands import Option
from discord.commands import slash_command
from discord.ext import commands

class Test(commands.Cog):
    def __init__(self, bot):
        self.bot = bot

    @slash_command(guild_ids=config.general_guilds)
    async def test(self, ctx,
        option: Option(str, ("my option"), required=False, default="")):

        await ctx.respond(content=str(option))

def setup(bot):
    bot.add_cog(Test(bot))
```

### Expected Results

that `option` is ""

### Actual Results

`option` is `None`

### Intents

default

### System Information

- Python v3.9.4-final
- py-cord v2.0.0-alpha
    - py-cord pkg_resources: v2.0.0a4148+g2bbf0639
- aiohttp v3.7.3

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

**Comment by CodeWithSwastik** [comment]
This has been fixed

**Comment by Snawe** [comment]
Are you sure @CodeWithSwastik ? I just checked out the master and `""` still gets converted to `None`

**Comment by CodeWithSwastik** [comment]
Can you confirm that you are on the latest commit? It worked fine for me

**Comment by Snawe** [comment]
```
pip freeze | grep "py-cord"
py-cord==2.0.0a4323+g55e373a8
```

**Comment by Snawe** [comment]
master branch, right?

**Comment by Lulalaby** [comment]
The newest commits hash is `55e373a8b34fb6d1cfd5c57417aa1857561be7dd`

**Comment by CodeWithSwastik** [comment]
It seems to work fine for me. 
```py
    @slash_command()
    async def test(self, ctx, arg=""):
        await ctx.respond(content=len(arg))
```
![image](https://user-images.githubusercontent.com/61446939/140381189-6e716cb1-a065-425d-8273-d8c599a8d957.png)
![image](https://user-images.githubusercontent.com/61446939/140381368-1e693d22-2d71-4995-8996-b183b7c71deb.png)

**Comment by Snawe** [comment]
Maybe its just late for me, but I am on 55e373a8b34fb6d1cfd5c57417aa1857561be7dd. Or am I?^^

![grafik](https://user-images.githubusercontent.com/17966466/140382363-889c3d1b-d261-4cf0-a49a-a21fa49dee91.png)
![grafik](https://user-images.githubusercontent.com/17966466/140382594-c248c99d-3487-46f1-a90f-344e967f9f66.png)
😢

**Comment by Snawe** [comment]
But yes @CodeWithSwastik, it works if you do it with your code.. But I am using `Option` and if you do it like I wrote in the inital bug report:
```py
    @slash_command()
    async def test(self, ctx,
        option: Option(str, ("my option"), required=False, default="")):

        await ctx.respond(content=str(option))
```
it does not work. So IMHO the bug isn't solved.

IMHO the issue is the line `option.default = option.default or p_obj.default`

**Comment by CodeWithSwastik** [comment]
> IMHO the issue is the line `option.default = option.default or p_obj.default`

That line was fixed though 🤔 https://github.com/BobDotCom/pycord/commit/5bcd060021441cbecc284729bfeef469b45f7c74
I'll have to look at it

**Comment by CodeWithSwastik** [comment]
Ah my bad, that was commited in Bob's fork and not in the repo. I'll fix it.

**Comment by Snawe** [comment]
ok? pip freeze now says I am on fcee9ea3.. which is current master again.. but I still have `option.default = option.default or p_obj.default` and not `option.default = option.default if option.default is not None else p_obj.default`. Looks like it isn't in master yet.

**Comment by Snawe** [comment]
ah, perfect. thanks! 👍  :)
