### ISSUE TITLE
discord.Permissions.all() not including start_embedded_activities and manage_members

### ISSUE THREAD

**Issue by Ruelf** [Pycord-Development/pycord#565]
### Summary

`discord.Permissions.all()` does not include `start_embedded_activities` and `manage_members`, while the docstring says all permissions are set to True

### Reproduction Steps

See Minimal Reproducible Code

### Minimal Reproducible Code

```python
import discord


permissions = discord.Permissions.all()

print(permissions.start_embedded_activities)
print(permissions.manage_members)
```

### Expected Results

The following is printed:
```
True
True
```

### Actual Results

The following is printed:
```
False
False
```

### Intents

members, guilds, guild_messages, guild_reactions

### System Information

- Python v3.10.0-final
- py-cord v2.0.0-alpha
    - py-cord pkg_resources: v2.0.0a4514+g125db3ab
- aiohttp v3.7.4.post0
- system info: Windows 10 10.0.19042

### Checklist

- [x] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

### Additional Context

Discord: Juno#6096

**Comment by plun1331** [comment]
Can reproduce, also applies to `Permissions.voice()` not having the `start_embedded_activities` permission.

**Comment by HyperGH** [comment]
Pretty sure this was fixed in #607

**Comment by Lulalaby** [comment]
I am against adding it.
Discord still don't want you to use it.
