### ISSUE TITLE
Cannot create slash groups in cogs

### ISSUE THREAD

**Issue by Revnoplex** [Pycord-Development/pycord#638]
### Summary

i tried creating a slash command group in my cogs using SlashCommandGroup

### Reproduction Steps

attempt to make slash command group in a cog

### Minimal Reproducible Code

```python
class Encoding(commands.Cog):
    """:printer:\\rencode and decode text in utf-8, ascii, base64, etc."""
    def __init__(self, client):
        self.client = client

    slash_bin = SlashCommandGroup(name='bin',
                                  description="encode and decode binary. Format:`8-bit separated binary`",
                                  guild_ids=config.slash_guilds)
```

### Expected Results

to create the slash command group

### Actual Results

Traceback (most recent call last):
  File "/ProjectDirectory/venv/lib/python3.10/site-packages/discord/ext/commands/bot.py", line 548, in _load_from_module_spec
    spec.loader.exec_module(lib)  # type: ignore
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/ProjectDirectory/cogs/Encoding.py", line 11, in <module>
    class Encoding(commands.Cog):
  File "/ProjectDirectory/venv/lib/python3.10/site-packages/discord/cog.py", line 182, in __new__
    new_cls.__cog_commands__ = tuple(c._update_copy(cmd_attrs) for c in new_cls.__cog_commands__)  # type: ignore
  File "/ProjectDirectory/venv/lib/python3.10/site-packages/discord/cog.py", line 182, in <genexpr>
    new_cls.__cog_commands__ = tuple(c._update_copy(cmd_attrs) for c in new_cls.__cog_commands__)  # type: ignore
AttributeError: 'SlashCommandGroup' object has no attribute '_update_copy'

### Intents

default intents, members and presences

### System Information

- Python v3.10.1-final
- py-cord v2.0.0-alpha
    - py-cord pkg_resources: v2.0.0a4480+g1df0afa1
- aiohttp v3.7.4.post0
- system info: Linux 5.11.0-43-generic #47~20.04.2-Ubuntu SMP Mon Dec 13 11:06:56 UTC 2021

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

**Comment by Makiyu-py** [comment]
I've tested this on the [cog slash groups example](/Pycord-Development/pycord/blob/master/examples/app_commands/slash_cog_groups.py) with the latest commit (for my test, that would be `2.0.0a4644+gf5c3e600`), it works as excepted.

But when I tested this with the minimal reproducible code, that error doesn't pop up, which is great, up until... __a different one shows!__
```
Traceback (most recent call last):
  File "main.py", line 8, in <module>
    class Encoding(commands.Cog):
  File "/ProjectDir/venv/lib/python3.8/site-packages/discord/cog.py", line 189, in __new__
    new_cls.__cog_commands__ = tuple(c._update_copy(cmd_attrs) for c in new_cls.__cog_commands__)  # type: ignore
  File "/ProjectDir/venv/lib/python3.8/site-packages/discord/cog.py", line 189, in <genexpr>
    new_cls.__cog_commands__ = tuple(c._update_copy(cmd_attrs) for c in new_cls.__cog_commands__)  # type: ignore
  File "/ProjectDir/venv/lib/python3.8/site-packages/discord/commands/commands.py", line 915, in _update_copy
    return self.copy()
  File "/ProjectDir/venv/lib/python3.8/site-packages/discord/commands/commands.py", line 887, in copy
    ret = self.__class__(
TypeError: type object got multiple values for keyword argument 'name'
```

I suspect that it has to do something with your minimal reproducible code's `SlashCommandGroup` arguments all being kwargs, when the `name` and `description` aren't really. Because of this, it gives multiple values of those arguments when copying the command group. This is a topic for a separate issue :D

**Comment by Dorukyum** [comment]
> I've tested this on the [cog slash groups example](/Pycord-Development/pycord/blob/master/examples/app_commands/slash_cog_groups.py) with the latest commit (for my test, that would be `2.0.0a4644+gf5c3e600`), it works as excepted.
> 
> But when I tested this with the minimal reproducible code, that error doesn't pop up, which is great, up until... **a different one shows!**
> 
> ```
> Traceback (most recent call last):
>   File "main.py", line 8, in <module>
>     class Encoding(commands.Cog):
>   File "/ProjectDir/venv/lib/python3.8/site-packages/discord/cog.py", line 189, in __new__
>     new_cls.__cog_commands__ = tuple(c._update_copy(cmd_attrs) for c in new_cls.__cog_commands__)  # type: ignore
>   File "/ProjectDir/venv/lib/python3.8/site-packages/discord/cog.py", line 189, in <genexpr>
>     new_cls.__cog_commands__ = tuple(c._update_copy(cmd_attrs) for c in new_cls.__cog_commands__)  # type: ignore
>   File "/ProjectDir/venv/lib/python3.8/site-packages/discord/commands/commands.py", line 915, in _update_copy
>     return self.copy()
>   File "/ProjectDir/venv/lib/python3.8/site-packages/discord/commands/commands.py", line 887, in copy
>     ret = self.__class__(
> TypeError: type object got multiple values for keyword argument 'name'
> ```
> 
> I suspect that it has to do something with your minimal reproducible code's `SlashCommandGroup` arguments all being kwargs, when the `name` and `description` aren't really. Because of this, it gives multiple values of those arguments when copying the command group. This is a topic for a separate issue :D

This should have been fixed recently.

**Comment by Revnoplex** [comment]
it still occurs positional arguments, i'll try the latest commit
